---
- name: Получение дистрибутива
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
    dest: "/tmp/vector-{{ vector_version }}.deb"
    mode: '0644'
  tags:
    - vector
    - distr
  become: true

- name: Обновление apt
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Установка vector
  ansible.builtin.command:
    cmd: "dpkg -i /tmp/vector-{{ vector_version }}.deb"
  changed_when: false
  tags:
    - vector
    - distr
  become: true  

- name: Применение конфигурации из файла 
  ansible.builtin.template:
    src: vector.yaml.j2
    dest: "{{ vector_config_path }}"
    mode: '0644'
  notify: Start vector service
  tags:
    - vector
    - config
  become: true

- name: Перезапуск сервиса
  ansible.builtin.meta: flush_handlers
  tags:
    - vector
    - restart service
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes
  become: true  
