---
<<<<<<< HEAD
- name: Получение дистрибутива
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
    dest: "/tmp/vector-{{ vector_version }}.deb"
    mode: '0644'
  tags:
    - vector
    - distr
  become: true

- name: Обновление apt
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Установка vector
  ansible.builtin.command:
    cmd: "dpkg -i /tmp/vector-{{ vector_version }}.deb"
  changed_when: false
  tags:
    - vector
    - distr
  become: true  

- name: Применение конфигурации из файла 
  ansible.builtin.template:
    src: vector.yaml.j2
    dest: "{{ vector_config_path }}"
    mode: '0644'
  notify: Start vector service
  tags:
    - vector
    - config
  become: true

- name: Перезапуск сервиса
  ansible.builtin.meta: flush_handlers
  tags:
    - vector
    - restart service
=======
- name: Установить nginx и git
  ansible.builtin.apt:
    name:
      - nginx
      - git
    state: present
    update_cache: yes
  become: true

- name: Клонировать репозиторий LightHouse
  ansible.builtin.git:
    repo: "{{ lighthouse_repo }}"
    dest: "{{ lighthouse_root }}"
    version: master
    force: yes
  become: true  

- name: Создать конфигурацию Nginx из шаблона
  ansible.builtin.template:
    src: lighthouse_nginx.conf.j2
    dest: "{{ lighthouse_nginx_conf_path }}"
    mode: '0644'
  become: true  

- name: Включить конфигурацию сайта в Nginx
  ansible.builtin.file:
    src: "{{ lighthouse_nginx_conf_path }}"
    dest: /etc/nginx/sites-enabled/lighthouse
    state: link
    force: yes
  become: true  

- name: Отключить дефолтный сайт Nginx
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true

- name: Проверить конфигурацию Nginx
  ansible.builtin.command: nginx -t
  register: nginx_check
  changed_when: false
  failed_when: nginx_check.rc != 0
  become: true

- name: Перезапустить и включить nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes
>>>>>>> beefe3c (Lighthouse role)
  become: true  